---
- name: Install Nginx  
  hosts: localhost
  become: true


tasks:
- name: get service facts
  service_facts:

- name: Check if nginx is present or not  
  yum: 
    name: nginx 
    state: latest
  when: ansible_facts.services["nginx.service"] is not defined

- name: copy the latest conf file
  copy:
    dest: /etc/nginx/nginx.conf
    src:  $WORKSPACE/nginx.conf
  notify: Nginx Reload
  
handlers:
- name:  Nginx Reload
  service: 
    name: nginx
    state: reload   

