---
- hosts: localhost
- become: true


tasks:
- name: get service facts
  service_facts:

- name: Check if nginx is present or not  
  fail:
       msg: Nginx is not installed
     when: ansible_facts.services["nginx.service"] is not defined
